### ISSUE TITLE
项目依赖整体升级后，在HBuildex 中运行到 真机/模拟器，项目报错如下：

### ISSUE THREAD

**Issue by hgpll** [ATQQ/uni-app-template#2]
``` sh
17:38:20.584 /Users/xxxxx/CompanyGit/xinyue-erp-app/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.4_hij5q53p4cvnckveypk6xau7he/node_modules/vite/dist/node-cjs/publicUtils.cjs:64
17:38:20.588     const cache = options.cache ?? new SplitVendorChunkCache();
17:38:20.596                                  ^
17:38:20.600 SyntaxError: Unexpected token '?'
17:38:20.600     at wrapSafe (internal/modules/cjs/loader.js:915:16)
17:38:20.603     at Module._compile (internal/modules/cjs/loader.js:963:27)
17:38:20.603     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
17:38:20.607     at Module.load (internal/modules/cjs/loader.js:863:32)
17:38:20.610     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
17:38:20.610     at Module.require (internal/modules/cjs/loader.js:887:19)
17:38:20.613     at require (internal/modules/cjs/helpers.js:74:18)
17:38:20.616     at Object.<anonymous> (/Users/hanpanpan/CompanyGit/xinyue-erp-app/node_modules/.pnpm/registry.npmmirror.com+vite@3.2.4_hij5q53p4cvnckveypk6xau7he/node_modules/vite/index.cjs:7:31)
17:38:20.620     at Module._compile (internal/modules/cjs/loader.js:999:30)
17:38:20.620     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by ATQQ** [comment]
看这个issue 挺久了，之前忘回复了 不知道这个问题还存在不

这个像HbuildeX版本不兼容一些ES语法

可以装Alpha版本试试
